! access to buy book, if true - bookstore is open, false - bookstore is close
! key/value
bookstore.allow.changing.availability=true

! path to the file for saving our data
! key/value
bookstore.file.saving.path=saving.bin
