! access to buy book, if true - bookstore is open, false - bookstore is close
! key/value
bookstore.allow.changing.availability=true

! path to the file for saving our data
! key/value
bookstore.file.saving.path=saving.bin


! Database connectivity
db.url=jdbc:mysql://localhost:3306/bookstore_db
db.username=root
db.password=root
# ????????? ???? Hikari
db.hikari.maximum-pool-size=10
db.hikari.connection-timeout=30000
db.hikari.idle-timeout=600000
